apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-service
  name: webapp-service
  namespace: default
spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: webapp
  sessionAffinity: None
  type: ClusterIP