apiVersion: v1
kind: Service
metadata:
  name: ingress-upstream
  labels:
    app: ingress-upstream
spec:
  selector:
    app: varnish-cache
  ports:
    - name: 80-to-80
      protocol: TCP
      port: 80
      targetPort: 80
